### ISSUE TITLE
Handle github login errors

### ISSUE THREAD

**Issue by hornofj** [Einstore/EinstoreAdmin#57]
![Bildschirmfoto 2019-04-26 um 11 26 58](https://user-images.githubusercontent.com/2500352/56798011-4c4a0780-6816-11e9-85d5-76cb635f629d.png)

deadlock: can't try again with different account after getting this error

**Comment by rafiki270** [comment]
Yes, this is a problem ... for now you can log yourself out on github in the authorised apps section

**Comment by ViliamKopecky** [comment]
These might be two separate problems... the github error doesnt actually travel all the way to the admin. And i think it doesnt relate to the error that you cannot try again, or at least it is not admin issue

**Comment by rafiki270** [comment]
We need to attach the error to the actual frontend response callback which contains the user info ... in case of an error we need to append an error object

**Comment by rafiki270** [comment]
And yes, these are two issues ... if you are not a member of any team no form of authentication should go through at all ... meaning, you should not be caught in the above mentioned deadlock. 

Second issue will be resolved by api passing on the error object onto the redirect lonk instead of displaying it.

Same problems will have to be implemented for gitlab

**Comment by hornofj** [comment]
closed in favor of this one:
https://github.com/Einstore/Einstore/issues/101
